(() => {
  const S = (id, title, build, lessons, official, contract, sanity, failures, hints, experiment) => ({ id, title, build, lessons, official, contract, sanity, failures, hints, experiment });
  const C = (input, output, invariants, forbidden) => ({ input, output, invariants, forbidden });
  const E = (hypothesis, prediction, run, observe) => ({ hypothesis, prediction, run, observe });
  const L = (href, label) => ({ href, label });
  const bank = window.MIT65840AssignmentBank = {};

  bank['ass01-mapreduce'] = {
    title: 'Lab 1 · MapReduce', capability: ['任务状态建模', '并发调度', '失败重派', '证据驱动验证'],
    source: { label: 'Spring 2026', url: 'https://pdos.csail.mit.edu/6.824/labs/lab-mr.html', repo: 'git://g.csail.mit.edu/6.5840-golabs-2026' },
    stages: [
      S('model', '任务、尝试与文件模型', '一张不会把 logical task、worker 与 attempt 混在一起的状态机。', [L('../0001-introduction-mapreduce.html#mr-wordcount-by-hand', 'Lecture 1 · M×R 数据流')], ['introduction', 'sequential-baseline', 'implementation-files'], C('输入文件、M/R 数量、Map/Reduce 插件', '稳定编号的 task 与可发布文件', ['每个 logical task 最终只贡献一次结果', 'Reduce 覆盖全部 M 个 Map 分区'], ['把 worker ID 当 task ID', '让半写文件成为稳定输出']), '用 2 个 Map、2 个 Reduce 在纸上列出四个中间文件；杀死某 worker 后，圈出必须重建的文件。', [['输出偶尔缺 key', '先检查 Reduce 是否覆盖所有逻辑 Map，而不是所有存活 worker。'], ['重复输出', '检查 attempt 完成与 logical task 接受结果是否分离。']], ['Concept：回到 task ≠ attempt。', 'Invariant：发布前文件必须完整，且同一 task 只能有一个 accepted result。', 'Debug：打印 task/attempt/file 表，不先跑完整测试。'], E('稳定身份与原子发布能吸收重复 attempt。', '强制两个 attempt 完成同一 task，最终输出仍只出现一次。', '在 tiny input 上人为延迟一个 worker。', '记录哪个 attempt 被接受、其他输出如何被隔离。')),
      S('scheduling', '并发调度与阶段门槛', '能并行发放 Map/Reduce、又不会跨越阶段依赖的 coordinator。', [L('../0005-go-patterns.html#go-state-ownership-table', 'Lecture 5 · Go 状态所有权')], ['manual-run', 'scheduling-hints', 'rpc-hints'], C('worker 的取任务/完成 RPC', '并发安全的 task 分配与等待/退出响应', ['同一空闲 task 的状态转换是原子的', '所有 Map accepted 后才发 Reduce'], ['持锁执行插件或大 I/O', '用固定 sleep 假装阶段完成']), '两个 worker 同时请求，而系统只剩一个 idle task；预期只有一个拿到该 task。', [['race test 报共享状态冲突', '先缩到 coordinator task table 的一次读写。'], ['Reduce 过早启动', '检查门槛统计的是 accepted logical Map，不是 reply 数量。']], ['Concept：所有 RPC handler 会并发执行。', 'Invariant：选择 task 与标记 in-progress 必须在同一临界区。', 'Debug：只跑并行测试，打印每次状态迁移。'], E('动态领取让快 worker 自动承担更多任务。', '异质 worker 下完成数不均，但总时间比静态均分短。', '给一个 worker 注入稳定延迟。', '比较 worker 完成数与作业总时长。')),
      S('failure', '超时、重派与迟到完成', '把 timeout 变成怀疑，而不是错误的 crash 证明。', [L('../0002-rpc-threads.html#rpc-under-failure', 'Lecture 2 · RPC 不确定性')], ['official-tests', 'scheduling-hints'], C('开始时间、attempt 身份、完成报告', '可重派且能拒绝/幂等处理迟到结果的状态机', ['timeout 可创建替代 attempt', '迟到报告不能让状态倒退'], ['假设 timeout 后旧 worker 已停止', '把整个作业重置']), '让 attempt A 超时、派出 B，然后按 A→B 与 B→A 两种顺序报告完成。两条时间线都应满足同一发布不变量。', [['崩溃测试偶发挂住', '检查超时扫描、等待状态与退出条件是否形成闭环。'], ['任务从 done 回到 running', '检查完成 RPC 是否验证当前状态/attempt。']], ['Concept：timeout 只说明不知道。', 'Invariant：accepted result 单调，done 不回退。', 'Debug：为每条报告打印旧状态、attempt、决策与新状态。'], E('重派改善故障恢复，但过早超时会制造重复工作。', '缩短 timeout 会降低真故障等待，却增加慢 worker 的重复 attempt。', '固定一组 task 时长，扫描 timeout。', '记录完成时间、重复 attempt 数与发布冲突。')),
      S('evidence', '端到端证据与 Gate', '不仅 tests green，还能说明为什么系统在失败路径正确。', [L('../0010-raft-lab-qa.html#raft-test-strategy', 'Lecture 10 · 测试策略')], ['official-tests', 'data-format-hints', 'submission'], C('tiny tests、官方 tests、race detector、日志', '可重复的正确性证据包', ['顺序参考输出一致', '并行/崩溃/race 都被覆盖'], ['只跑一次全套测试', '把 connection refused 当所有 bug 的解释']), '用三个短文件手算 wc 输出，先比较顺序版，再比较分布式版排序并集。', [['单测过、全套偶发失败', '寻找泄漏 goroutine、残留文件和跨测试状态。'], ['-race 才失败', '先定位第一对冲突访问，不用 sleep 掩盖。']], ['Concept：测试是观测，不是证明。', 'Invariant：每个失败都有可解释的状态迁移。', 'Debug：固定 seed、重复单测、再扩大到全套。'], E('正确实现对 worker 数量和完成顺序不敏感。', '1/2/5 个 worker 的逻辑输出相同，时序与耗时不同。', '保存配置、重复次数和输出 hash。', '解释差异是性能还是语义。'))
    ]
  };

  bank['ass02-key-value-server'] = {
    title: 'Lab 2 · Key/Value Server', capability: ['RPC 语义', '线性一致操作', '去重与 GC', '不可靠网络实验'],
    source: { label: 'Spring 2026', url: 'https://pdos.csail.mit.edu/6.824/labs/lab-kvsrv1.html', repo: 'git://g.csail.mit.edu/6.5840-golabs-2026' },
    stages: [
      S('semantics', '先写可见语义', 'Get/Put/Append 在成功、timeout 与 retry 下的结果表。', [L('../0002-rpc-threads.html#rpc-semantics-derivation', 'Lecture 2 · RPC 语义推导'), L('../0008-linearizability.html#linear-history-method', 'Lecture 8 · 线性化点')], ['introduction', 'kv-semantics'], C('client operation 与网络结果', '明确的 value/reply 与不确定结果语义', ['每个完成操作有线性化点', 'timeout 不证明未执行'], ['把 transport success 当 operation correctness', '用 wall clock 猜请求是否执行']), '单 key 初值 A，两个 client 分别 Append B/C；列出所有允许的最终值与不允许的撕裂值。', [['值正确但 history 不可线性化', '检查锁覆盖的状态转换是否与 reply 对应。'], ['timeout 后重复 Append', '检查逻辑 request 身份是否跨 retry 保持。']], ['Concept：retry 是新消息，不一定是新操作。', 'Invariant：完成 reply 对应一次原子状态转换。', 'Debug：先画一条请求/执行/reply 时间线。'], E('可靠网络下简单锁足够形成线性化点。', '并发操作顺序可变，但每次结果都能排成合法串行历史。', '记录 invocation/response 与 server commit 日志。', '给出一种合法顺序，而不是只看最终值。')),
      S('server', '可靠网络下的 KV 与 Lock', '最小并发安全 server/client，以及建立在原子 KV 上的锁。', [L('../0005-go-patterns.html#go-state-ownership-table', 'Lecture 5 · 状态所有权')], ['getting-started', 'reliable-kv', 'reliable-lock'], C('并发 Get/Put/Append', '线性一致的内存 KV 和 lock protocol', ['map 的读改写原子', 'lock ownership 由值协议表达'], ['跨 RPC 持有本地 mutex', '依赖 client 调度公平性作为安全条件']), '两个 goroutine 各 Append 100 次；长度必须精确增长 200，顺序无需预设。', [['race detector 报 map 冲突', '锁定最小共享状态所有者。'], ['两个 client 都认为持锁', '检查 acquire 是否是原子 compare/update 语义。']], ['Concept：mutex 保护 server 内状态，不跨网络。', 'Invariant：lock owner 的一次变化必须对应一个线性化操作。', 'Debug：先串行跑 acquire/release，再加入两个 client。'], E('将锁建立在 KV 原语上会继承 KV 的一致性边界。', '可靠网络下正确；丢 reply 后 ownership 判断出现歧义。', '分别运行 reliable 与 reply-loss 场景。', '指出哪一步从确定变为未知。')),
      S('failures', '不可靠网络与去重生命周期', '在丢请求/丢回复下避免非幂等写重复生效。', [L('../0002-rpc-threads.html#rpc-under-failure', 'Lecture 2 · ambiguous timeout')], ['dropped-messages', 'unreliable-lock'], C('clientID、sequence、ack 水位与 operation', 'at-most-once 可见效果和可回收去重状态', ['同一逻辑请求重复到达只返回同一结果', '回收前证明 client 不再重试'], ['reply 发出后立即删除结果', '用时间阈值替代协议确认']), '让 Append 执行、丢 reply、重试三次；最终值只能追加一次，三次 reply 语义应一致。', [['值被追加两次', '检查 request ID 是否在 retry 时变化。'], ['内存持续增长', '检查 client 是否发送已确认序号/水位。']], ['Concept：缓存的是结果，不只是 seen 标志。', 'Invariant：重复请求必须重放相同 reply。', 'Debug：用一个 client、一个 seq，枚举请求/回复丢失。'], E('去重把网络重试成本换成 server 状态。', '消息丢失率升高时请求次数增加，但逻辑更新次数不变。', '扫描丢包率并记录 attempts、dedup entries。', '区分传输次数与可见操作次数。')),
      S('evidence', '语义证据与 Gate', '用 history 而不是“最后值看起来对”验证实现。', [L('../0008-linearizability.html#linear-duplicates', 'Lecture 8 · 重试历史')], ['final-check'], C('并发 history、网络配置、测试结果', '可复现的 safety/liveness 证据', ['完成操作可线性化', '网络恢复后请求最终推进'], ['只检查最终值', '把无限重试当正确性']), '记录 3 个 operation 的 invocation/response interval，手工找线性化顺序。', [['偶发错误无法复现', '保存 seed、operation history 与网络 fault 序列。'], ['永远重试但测试没结束', '区分 safety 未破坏与 liveness 已丢失。']], ['Concept：最终状态丢失了历史信息。', 'Invariant：real-time precedence 必须保留。', 'Debug：缩成一个 key、两个 client、三次 operation。'], E('去重保证 safety，retry policy 影响 liveness 与负载。', '更激进重试不改变结果，但会放大 RPC。', '固定 fault trace 比较 backoff 策略。', '同时报告成功时间和 RPC 数。'))
    ]
  };

  bank['ass03-raft'] = {
    title: 'Lab 3 · Raft', capability: ['leader election', '并发日志复制', '持久化', 'snapshot 与压力验证'],
    source: { label: 'Spring 2026', url: 'https://pdos.csail.mit.edu/6.824/labs/lab-raft1.html', repo: 'git://g.csail.mit.edu/6.5840-golabs-2026' },
    stages: [
      S('election', 'Term、投票与选举', '可在丢包与分区下维持 Election Safety 的 peer。', [L('../0006-raft-1.html#raft-election-by-hand', 'Lecture 6 · 手推选举'), L('../0004-paxos.html#paxos-quorum-safety', 'Lecture 4 · quorum safety')], ['setup-interface', 'part-3a'], C('RequestVote/heartbeat/timer', '单调 term、持久 vote、角色转换', ['每 term 至多一票', '看到更大 term 立即降级'], ['重置 timer 时不说明触发事件', '把 candidate 超时当 leader 证明']), '三节点同时 timeout；手推每条 vote reply，确认同一 term 不会产生两个多数派 leader。', [['同一 term 双 leader', '检查 vote 持久化与原子检查/赋值。'], ['频繁无 leader', '检查 timer 随机化与合法重置点。']], ['Concept：多数派交集只在投票约束成立时有用。', 'Invariant：currentTerm 单调、votedFor 每 term 单值。', 'Debug：固定 3 节点与 timer seed，记录 term/role/vote。'], E('随机 timeout 降低 split vote 概率。', '扩大 timeout spread 后选举轮数下降，failover 延迟可能上升。', '固定网络，扫描 timeout 范围。', '报告选举耗时和 term 增量。')),
      S('concurrency', '并发与 RPC 生命周期', '不会让旧 reply 污染新 term 的 Go 实现骨架。', [L('../0005-go-patterns.html#go-unlock-rpc-proof', 'Lecture 5 · unlock/RPC/revalidate')], ['debug-guidance'], C('共享 Raft state、goroutine、RPC reply', '明确锁纪律、退出协议和陈旧结果校验', ['RPC 参数在发送前形成稳定快照', 'reply 回来重新验证 term/role'], ['持锁等待网络', 'reply 成功就无条件更新 nextIndex']), 'term 5 发 RPC，等待时升到 term 7；reply 返回后列出允许和禁止的状态更新。', [['-race 报 log/term 冲突', '检查 slice alias 是否逃出锁。'], ['测试结束后仍有日志', '检查 Kill 与后台 goroutine 退出路径。']], ['Concept：异步结果有出生版本。', 'Invariant：旧 term reply 不推进新 term 状态。', 'Debug：给每个 RPC 打印 sendTerm/currentTerm。'], E('复制参数后解锁发 RPC 可提高进展又保持快照稳定。', '锁等待时间降低；陈旧 reply 数可能增加但被丢弃。', '在延迟网络记录锁等待和 stale reply。', '解释 throughput 与重试成本的变化。')),
      S('replication', '日志匹配与提交', '能回退冲突日志、只提交安全条目的 leader replication。', [L('../0007-raft-2.html#raft-current-term-commit', 'Lecture 7 · current-term commit')], ['part-3b'], C('AppendEntries、nextIndex/matchIndex、commitIndex', '满足 Log Matching 与 Leader Completeness 的复制状态机', ['成功匹配前缀后才追加', 'leader 只用多数派直接提交 current-term entry'], ['按最大副本数提交旧 term entry', '并发 RPC reply 让 nextIndex 倒退']), '构造 leader [1,1,4]、follower [1,2,2]，逐次写出 prev index/term 与回退后的日志。', [['日志永久追不上', '检查冲突回退和 heartbeat 是否都走同一一致性检查。'], ['分区恢复后错误提交', '检查 current-term gate 和 commitIndex 单调性。']], ['Concept：复制成功不等于已提交。', 'Invariant：nextIndex 不由陈旧 reply 倒退，commitIndex 单调。', 'Debug：一次只跟踪一个 leader-follower 对。'], E('冲突提示可减少逐项回退 RPC。', '长冲突前缀下 RPC 数下降，最终日志相同。', '构造不同冲突长度比较。', '同时报告 RPC 与字节数。')),
      S('persistence-snapshot', '持久化与 Snapshot 边界', '崩溃后不丢安全证据，并能压缩已应用前缀。', [L('../0007-raft-2.html#raft-snapshot-boundary', 'Lecture 7 · snapshot boundary')], ['part-3c-persistence', 'part-3d-snapshot', 'part-3d-tests'], C('persistent term/vote/log、snapshot metadata', '原子恢复的 Raft state 与绝对 log index 映射', ['reply 前持久化安全相关状态', 'snapshot 边界 index/term 与 state machine 对齐'], ['截断后把 slice offset 当绝对 index', '先回复再异步 persist']), 'snapshot through index 5 后仅保留 6..8；手算 absolute index 7 对应的 slice offset。', [['重启后偶发双投票', '检查 votedFor/currentTerm 的 persist 时机。'], ['装 snapshot 后 index 越界', '集中定义 absolute↔offset 转换。']], ['Concept：持久状态是跨崩溃协议证据。', 'Invariant：snapshot state 与 lastIncludedIndex/Term 原子对应。', 'Debug：每次截断后打印 absolute range 和 offset 0 含义。'], E('snapshot 用 CPU/I/O 换受控日志与恢复时间。', '阈值更低时 snapshot 更频繁、日志更小。', '扫描阈值并测日志字节、snapshot 次数。', '说明 peak 与 steady-state 差异。')),
      S('evidence', '对抗性测试与 Gate', '用 timeline 和不变量解释 flaky failure。', [L('../0010-raft-lab-qa.html#debug-rpc-timeline', 'Lecture 10 · RPC timeline')], ['debug-guidance'], C('seed、网络事件、term/log timeline', '可复现失败与最小不变量证据', ['之前 parts 不回归', 'race/重复运行/长测试都覆盖'], ['只增加 sleep', '只看最后一行 panic']), '保存一次失败前 30 条状态迁移，找第一条违反单调性或所有权的记录。', [['单测过、100 次失败', '固定 seed 并缩短日志到第一处状态分叉。'], ['日志很多但无法推理', '只打印 term/role/index/peer/原因，不打印整对象。']], ['Concept：第一条非法迁移比最终症状更有价值。', 'Invariant：为每条更新写 reason 与 precondition。', 'Debug：先复现，再最小化，再修复。'], E('协议 bug 通常对调度敏感。', '提高并发/丢包使失败率变化，但不决定 bug 类型。', '固定实现，扫描 network mode 与 repetitions。', '报告失败率和共同最早不变量。'))
    ]
  };

  bank['ass04-kv-raft'] = {
    title: 'Lab 4 · Fault-tolerant KV', capability: ['RSM 边界', 'client 去重', 'Raft 应用', 'snapshot 生命周期'],
    source: { label: 'Spring 2026', url: 'https://pdos.csail.mit.edu/6.824/labs/lab-kvraft1.html', repo: 'git://g.csail.mit.edu/6.5840-golabs-2026' },
    stages: [
      S('rsm', '复制状态机 Contract', '把不可靠 Raft index 转成可等待、可失效的 operation future。', [L('../0008-linearizability.html#linear-history-method', 'Lecture 8 · linearization'), L('../0007-raft-2.html#raft-current-term-commit', 'Lecture 7 · commit/apply')], ['part-4a-rsm'], C('client op、Start(index/term)、applyCh', '按 log order 串行 apply 的 RSM wrapper', ['只有 applied command 改状态机', '等待者验证 index 上的 command identity'], ['Start 返回即回复 client', '无限等待已失去 leadership 的 index']), '同一 index 的旧 leader 等待 op A，新 leader提交 op B；A 的 waiter 必须识别 mismatch。', [['错误 client 收到成功', '检查 waiter 是否只按 index 唤醒而未验证 command。'], ['goroutine 永久等待', '检查 term/leadership 失效与 timeout 清理。']], ['Concept：log index 是位置，不是 command 身份。', 'Invariant：reply 必须对应实际 applied 的同一逻辑 op。', 'Debug：记录 start index/term 与 apply command ID。'], E('per-index waiter 简化 reply routing，但需处理 leadership change。', '分区越多，mismatch/timeout 增加，状态机结果仍一致。', '注入 leader change 于 Start 与 apply 之间。', '分类 success、mismatch、timeout。')),
      S('kv', 'KV 操作与 Client Retry', '线性一致 Get/Put/Append 穿过 Raft 完整闭环。', [L('../0002-rpc-threads.html#rpc-semantics-derivation', 'Lecture 2 · retry semantics')], ['part-4b-basic'], C('Clerk op + client/seq', '经 Raft committed/applied 后的 reply', ['所有读写都经过同一排序边界', 'wrong leader 不产生成功语义'], ['在 follower 本地直接读', '每次 retry 生成新 seq']), 'leader 在写提交后、reply 前崩溃；client retry 后最终只能观察一次逻辑更新。', [['读到旧值', '确认 Get 也经过共识顺序，而非本地 map。'], ['Append 重复', '检查 client seq 在 retry 间是否稳定。']], ['Concept：linearizable read 也需要排序/leader 证明。', 'Invariant：同一 client/seq 只 apply 一次。', 'Debug：一个 client 一个 key，先制造 reply loss。'], E('所有操作过 Raft 换来线性一致，但增加延迟。', '稳定 leader 下 latency 至少包含复制/提交路径。', '测本地 baseline 与 replicated op。', '分解 client、Raft commit、apply wait。')),
      S('dedup', '故障、重复与 Session 状态', '让 client retry 不把网络不确定性写进业务状态。', [L('../0008-linearizability.html#linear-duplicates', 'Lecture 8 · duplicate filtering')], ['part-4b-failures'], C('clientID/seq、last reply、snapshot', '持久且可恢复的 dedup session table', ['dedup 状态与 KV 一起复制/快照', 'duplicate 返回原 reply'], ['只在 leader 内存去重', '只存 seen 不存结果']), 'Append 返回旧值后 reply 丢失；duplicate 必须返回与第一次相同的旧值。', [['重启后重复生效', '检查 session table 是否进入 snapshot/Raft state。'], ['duplicate reply 不同', '检查是否缓存了语义 reply。']], ['Concept：去重表是状态机状态。', 'Invariant：KV 与 session table 同一 apply 顺序更新。', 'Debug：打印 client/seq、duplicate 命中和 reply。'], E('session state 增加内存但稳定 retry 语义。', 'client 数增长时 session state 近线性增长。', '固定 key，扫描 client 数。', '报告每 client 状态与回收假设。')),
      S('snapshot', 'KV + Session 的一致 Snapshot', '在 maxraftstate 约束下原子压缩完整应用状态。', [L('../0007-raft-2.html#raft-snapshot-boundary', 'Lecture 7 · snapshot boundary')], ['part-4c-snapshot'], C('KV、dedup sessions、lastApplied', '可由 snapshot 独立恢复的 state machine image', ['snapshot 包含所有可见状态', '只截断 ≤ lastApplied 的 log'], ['只快照 KV 不快照去重', '按 log size 瞬时值反复触发']), '快照后崩溃，再收到快照前已完成 Append 的 duplicate；结果仍不得重复。', [['恢复后值对但重复写', 'session table 未进 snapshot。'], ['snapshot storm', '检查触发阈值与异步生命周期。']], ['Concept：snapshot 是 state machine image，不只是值 map。', 'Invariant：lastApplied 与 image 对齐。', 'Debug：恢复后先跑 duplicate tiny case。'], E('snapshot 阈值在空间、CPU 和恢复时间间取舍。', '更小阈值减少 Raft log，增加编码频率。', '扫描 maxraftstate。', '同时记录 log bytes、snapshot count、latency tail。')),
      S('evidence', '端到端 Gate', '把线性一致、容错与空间边界放在同一证据包。', [L('../0010-raft-lab-qa.html#raft-test-strategy', 'Lecture 10 · test strategy')], ['final-validation'], C('history、fault trace、memory/log metrics', '可重复 correctness + resource evidence', ['故障恢复不改变语义', 'snapshot 后旧状态仍可验证'], ['只验证 happy path', '只用平均 latency']), '一个 key、两个 client、一次 leader crash、一次 snapshot，手工解释每个 reply。', [['值错但 Raft tests 都过', '问题可能在 RSM/waiter/dedup 边界。'], ['空间超限但功能正确', '检查 snapshot 触发和持久字节，而非对象数量。']], ['Concept：组件正确不等于组合边界正确。', 'Invariant：每个 success reply 有 committed/applied 证据。', 'Debug：逐层记录 Clerk→RSM→Raft→apply。'], E('故障改变 latency/retry，不应改变可见历史。', 'unreliable 模式 tail 上升，linearizability 仍成立。', '保存配置、seed、history。', '分别报告 safety 与 performance。'))
    ]
  };

  bank['ass05-sharded-kv'] = {
    title: 'Lab 5 · Sharded KV', capability: ['配置 epoch', '跨组路由', '迁移与回收', '并发重配置验证'],
    source: { label: 'Spring 2026', url: 'https://pdos.csail.mit.edu/6.824/labs/lab-shard1.html', repo: 'git://g.csail.mit.edu/6.5840-golabs-2026' },
    stages: [
      S('config', '配置 Epoch 与 Controller', '单调编号、确定映射、可查询的 shard 配置历史。', [L('../0009-zookeeper.html#zk-consistency-order', 'Lecture 9 · ordered metadata')], ['part-5a-config'], C('Join/Leave/Move/Query', '编号配置与 shard→group map', ['每次变更产生新 config', '相同状态输入得到确定映射'], ['原地修改历史 config', '用 map iteration 顺序决定分配']), '2 groups/4 shards 后加入第 3 group；检查移动数、均衡和同输入确定性。', [['测试偶发映射不同', '检查 unordered map tie-break。'], ['旧 Query 被新配置污染', '检查是否深拷贝 map/slice。']], ['Concept：配置是不可变 epoch snapshot。', 'Invariant：config number 单调，历史可查询。', 'Debug：打印每次输入、排序后 group IDs 与结果。'], E('更均衡的分配可能搬动更多 shards。', 'balance 与 movement 是两个指标。', '对同一 join 比较策略。', '报告 max-min load 与 moved shards。')),
      S('groups', 'Replica Group 与 Routing', '让 client 按 config 找 group，并能从 WrongGroup 恢复。', [L('../0012-spanner.html#spanner-2pc-paxos', 'Lecture 12 · shard/group 层次')], ['part-5a-static'], C('key、cached config、group endpoints', '路由到当前 owner 的 Clerk/server', ['server 只服务自己拥有的 shard', 'WrongGroup 触发配置刷新'], ['把 endpoint availability 当 ownership', '每次 RPC 无脑拉最新配置']), 'client 持有 config N，shard 已在 N+1 移动；列出一次 stale request 到最终成功的路径。', [['永久 WrongGroup loop', '检查刷新 config 与 server ownership epoch。'], ['两个 group 都接受写', '检查服务条件是否绑定 config state。']], ['Concept：配置决定 authority，不是连接成功。', 'Invariant：某 epoch 每 shard 只有一个 owner。', 'Debug：日志带 configNum/shard/gid。'], E('缓存配置减少 controller 负载但允许短暂 stale route。', '更新频率高时 WrongGroup/retry 增加。', '扫描 reconfiguration interval。', '报告 config queries 与 retries。')),
      S('migration', 'Shard 数据迁移', '搬运 KV 与 client session，不制造双主可见窗口。', [L('../0013-chain-replication.html#chain-failure-table', 'Lecture 13 · authority handoff')], ['part-5a-move'], C('old/new config、shard data、session state', '带 epoch 的 transferable shard image', ['KV 与 dedup session 一起迁移', '安装前验证目标 epoch/ownership'], ['只复制 values', '没有 epoch 地重复安装旧数据']), 'client Append 后 reply 丢失，随后 shard 迁移；新 group 收到 retry，结果必须只出现一次。', [['迁移后 duplicate 生效', 'dedup/session state 未随 shard 搬运。'], ['旧迁移覆盖新写', '缺少 config/epoch 校验。']], ['Concept：迁移对象是完整 state machine partition。', 'Invariant：数据、session、epoch 同一边界。', 'Debug：一个 shard、一个 key、一个 client seq。'], E('pull/push 选择影响依赖与重试，不改变 ownership invariant。', '网络故障下消息次数不同，最终 shard image 相同。', '固定 fault trace 比较协议。', '记录传输、安装、ack 与删除事件。')),
      S('recovery', '回收、重试与中间状态', '让迁移在 crash/duplicate/reorder 下可恢复。', [L('../0019-sundr.html#fork-consistency-trace', 'Lecture 19 · 不可合并历史直觉')], ['part-5b'], C('迁移 phase、epoch、ack、GC state', '幂等安装与有证明的旧副本回收', ['重试迁移不重复效果', '删除前有新 owner 持久接管证据'], ['收到 transfer request 就删旧数据', '用时间等待作为完成证明']), '新 group 安装成功但 ack 丢失；旧 group 重发。两边状态应如何幂等演进？', [['shard 永久卡 migrating', '检查每个中间状态是否有重试触发。'], ['偶发丢数据', '检查 GC 是否早于可恢复接管证据。']], ['Concept：ack 丢失使“已完成”成为分布式状态。', 'Invariant：删除依赖协议证据，不依赖时间。', 'Debug：逐个丢 transfer/install/ack 消息。'], E('保守 GC 提高安全余量但暂时占双份空间。', '延迟 GC 增加空间，降低不完整接管风险。', '注入 ack loss 并测重复 transfer/space。', '解释临时峰值与 steady state。')),
      S('concurrency', '并发请求与重配置', '在 client ops、config change、migration 交错时维持单一 authority。', [L('../0011-distributed-transactions.html#tx-state-table', 'Lecture 11 · 跨边界状态机')], ['part-5c'], C('client op、config op、migration op', '经各组 Raft 排序的 epoch-aware transitions', ['operation 只在匹配 ownership epoch 时 apply', '配置推进不能跳过所需迁移状态'], ['RPC 到达顺序等于全局顺序', '持锁跨组调用']), '把一个 client Put、config N+1、transfer 三个事件按六种顺序排列，标出允许的 apply 条件。', [['两个 group 都返回 success', 'authority check 没有进入复制状态机顺序。'], ['重配置下停滞', '检查跨组等待是否形成循环依赖。']], ['Concept：跨组没有单一共享锁。', 'Invariant：每次 apply 携带并验证 config epoch。', 'Debug：只启用一次 move 与一个并发 client。'], E('更频繁重配置提高管理敏捷性，也放大迁移干扰。', '吞吐下降、tail 增加，correctness 不变。', '扫描 move interval 与 client load。', '区分 migration bytes、retry 与 Raft latency。')),
      S('evidence', '全系统 Gate', '用 capability、history 与资源证据结束，而不只数测试。', [L('../0010-raft-lab-qa.html#raft-test-strategy', 'Lecture 10 · evidence-first debugging')], ['part-5d', 'submission'], C('配置史、operation history、fault trace、metrics', '可复现的 sharding correctness/performance 证据', ['所有完成操作可放入合法 epoch 历史', '故障后最终恢复进展'], ['只检查最终 config', '把测试 timeout 一律归因于机器慢']), '2 groups、1 shard、1 client、1 move、1 lost ack：闭卷解释完整事件链。', [['压力测试偶发丢 key', '先定位 key 的 ownership epoch 链，不从全局日志猜。'], ['正确但极慢', '测 config polling、迁移重试、持锁 RPC 与日志增长。']], ['Concept：sharding 增加的是 authority handoff，不只是路由。', 'Invariant：每个 key 在每个 epoch 有唯一可写 owner。', 'Debug：按 shard 过滤 event log。'], E('sharding 提高并行容量，重配置引入控制面和迁移成本。', '稳定配置可随 group 扩展；频繁 move 会侵蚀收益。', '固定 key 分布比较 stable/churn。', '报告 throughput、tail、migration bytes 和 retries。'))
    ]
  };
})();
